analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.928678
  lightness: 0.099444
  rhythmicContrast: 0.714069
  saturation: 0.543251
cta: {}
layout_spectrum: 0
name: angus
opengraph: {}
purpose: {}
typography_spectrum: 0.405405
